safe: true

title: Haythem OUEDERNI - Stratups enthusiastic and Web / Mobile apps Architect and Developer
email: haythem@nirbyapp.com
description: > # this means to ignore newlines until "baseurl:"
  "New technologies enthusiastic, I help startups and big companies build beautiful and rock solid mobile and web apps. 
  Intervienig from the strategy definition step to designing the architecture of the solution before putting it in place and developing it." 
image_to_share: TODO

organization : Haythem OUEDERNI

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  haythem-ouederni

# Mitosis on social medias
social_links:
  github: https://github.com/haythemOUE
  linkedin: https://www.linkedin.com/in/haythem-ouederni-16598977/




# facebook information
facebook_app_id: 

# Build settings
google_analytics_id: todo
google_site_verification: sIII5ZDXqWlrMwtfZym2jxmm8anSICOy8t7xqfAwTdQ

github_repository: https://github.com/haythemOUE/haythem-ouederni

haythem_ouederni_website: https://haythem-ouederni.github.io

timezone: Europe/Paris

markdown: kramdown
#theme: minima

highlighter: rouge

gems:
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - README.md

sass:
  sass_dir: _sass
  style: compressed

defaults:
  -
    scope:
      path: "" # for the file on the root
    values:
      layout: "default"
  -
    scope:
      path: "_docs"
    values:
      layout: "default"
  -
    scope:
      path: "pages"
    values:
      layout: "default"
